foodItemList = [
    'abiyuch',
    'acerola',
    'acorn',
    'agave',
    'agents',
    'agutuk',
    'alfalfa',
    'amaranth',
    'animal',
    'apache',
    'apple',
    'apples',
    'applesauce',
    'apricot',
    'apricots',
    'arrowhead',
    'arrowroot',
    'artichokes',
    'artificial',
    'arugula',
    'ascidians',
    'asparagus',
    'avocados',
    'baby',
    'babyfood',
    'bacon',
    'smoked bacon',
    'bagel',
    'bagels',
    'baking',
    'balls',
    'balsam-pear',
    'bamboo',
    'bananas',
    'bar',
    'barbecue',
    'barley',
    'bars',
    'basil',
    'bean',
    'beans',
    'bear',
    'beef',
    'minced beef',
    'ground beef',
    'beerwurst',
    'beet',
    'beets',
    'berry',
    'besan',
    'beverage',
    'beverages',
    'biscuits',
    'bison',
    'bits',
    'bitter',
    'blackberries',
    'blackberry',
    'blackeyes',
    'blend',
    'blueberries',
    'blueberry',
    'bockwurst',
    'bologna',
    'borage',
    'bowl',
    'boysenberries',
    'bran',
    'brand',
    'bratwurst',
    'braunschweiger',
    'bread',
    'breadfruit',
    'breakfast',
    'breast',
    'broadbeans',
    'broccoli',
    'broth',
    'brotwurst',
    'brussels',
    'buckwheat',
    'buffalo',
    'bulgur',
    'buns',
    'burdock',
    'burgers',
    'burrito',
    'butter',
    'butterbur',
    'butters',
    'cabbage',
    'cake',
    'candied',
    'candies',
    'capers',
    'carambola',
    'carbonated',
    'cardoon',
    'caribou',
    'carissa',
    'carne',
    'carob',
    'carob-flavor',
    'carrot',
    'carrots',
    'cassava',
    'catsup',
    'cattail',
    'cauliflower',
    'celeriac',
    'celery',
    'celtuce',
    'cereal',
    'cereals',
    'chard',
    'chayote',
    'cheese',
    'cheesecake',
    'cheesefurter',
    'cherimoya',
    'cherries',
    'chewing',
    'chicken',
    'chickpea',
    'chickpeas',
    'chicory',
    'five-spice',
    'chilchen',
    'child',
    'chili',
    'chips',
    'chiton',
    'chives',
    'chocolate',
    'chocolate-flavor',
    'chocolate-flavored',
    'chokecherries',
    'chorizo',
    'chrysanthemum',
    'cilantro',
    'cinnamon',
    'citronella',
    'citrus',
    'clam',
    'clementines',
    'cloudberries',
    'cockles',
    'cocktail',
    'cocoa',
    'coffee',
    'coffeecake',
    'collards',
    'commercially',
    'concentrate',
    'cone',
    'cones',
    'confectionery',
    'containing',
    'cookie',
    'cookies',
    'coriander',
    'corn',
    'corned',
    'cornmeal',
    'cornsalad',
    'cornstarch',
    'cotija',
    'couscous',
    'cowpeas',
    'crabapples',
    'cracker',
    'crackers',
    'cream crackers',
    'cranberries',
    'cranberry',
    'cranberry-apple',
    'cranberry-apricot',
    'cranberry-grape',
    'cranberry-orange',
    'cream',
    'creams',
    'creamy',
    'cress',
    'croissants',
    'croutons',
    'crumbs',
    'crust',
    'crustaceans',
    'cucumber',
    'currants',
    'custard-apple',
    'custards',
    'dairy',
    'dandelion',
    'danish',
    'dates',
    'deer',
    'dessert',
    'desserts',
    'diabetes',
    'dill',
    'dinner',
    'dip',
    'dishes',
    'dock',
    'dogs',
    'dough',
    'doughnuts',
    'dove',
    'dried porcini',
    'drink',
    'drippings',
    'dry',
    'duck',
    'dulce',
    'durian',
    'dutch',
    'ear',
    'edamame',
    'egg',
    'eggnog',
    'eggnog-flavor',
    'eggplant',
    'eggs',
    'elderberries',
    'elk',
    'emu',
    'endive',
    'energy',
    'entrees',
    'epazote',
    'eppaw',
    'extender',
    'extract',
    'falafel',
    'fast',
    'fat',
    'fava',
    'feijoa',
    'fennel',
    'fern',
    'ferns',
    'fiddlehead',
    'figs',
    'fillets',
    'fillings',
    'fireweed',
    'fish',
    'fish sauce',
    'flakes',
    'flan',
    'flavored',
    'flour',
    'flours',
    'flower',
    'flowers',
    'fluid',
    'focaccia',
    'foie',
    'food',
    'foods',
    'formula',
    'formulated',
    'frankfurter',
    'franks',
    'frijoles',
    'frog',
    'from',
    'frostings',
    'fruit',
    'fruit-flavored',
    'frybread',
    'frying',
    'fungi',
    'garbanzo',
    'garlic',
    'gelatin',
    'gelatins',
    'germ',
    'ginger',
    'gluten',
    'goat',
    'goose',
    'gooseberries',
    'gourd',
    'grain',
    'gram',
    'granola',
    'grape',
    'grapefruit',
    'grapes',
    'gras',
    'grass',
    'gravy',
    'green',
    'greens',
    'groats',
    'groundcherries',
    'grouse',
    'guacamole',
    'guanabana',
    'guava',
    'guavas',
    'guinea',
    'gum',
    'gums',
    'ham',
    'hazelnut',
    'hazelnuts',
    'headcheese',
    'hearts',
    'hen',
    'hibiscus',
    'hips',
    'hominy',
    'honey',
    'horned',
    'horseradish',
    'household',
    'huckleberries',
    'hummus',
    'hush',
    'hyacinth',
    'hyacinth-beans',
    'hydrogenated',
    'hydrolyzed',
    'ice',
    'imitation',
    'incaparina',
    'industrial',
    'isolate',
    'jackfruit',
    'jams',
    'java-plum',
    'jellies',
    'jellyfish',
    'jerusalem-artichokes',
    'jicama',
    'juice',
    'jujube',
    'jute',
    'kale',
    'kanpyo',
    'keikitos',
    'kielbasa',
    'kiwano',
    'kiwifruit',
    'knackwurst',
    'kohlrabi',
    'kumquats',
    'lamb',
    'lambs',
    'lambsquarters',
    'lard',
    'lasagna',
    'leavening',
    'leaves',
    'lebanon',
    'leche',
    'leeks',
    'legs',
    'lemon',
    'lemonade',
    'lemonade-flavor',
    'lemons',
    'lentils',
    'lettuce',
    'lima',
    'lime',
    'limeade',
    'limes',
    'link',
    'links',
    'lion',
    'litchis',
    'liver',
    'liverwurst',
    'loaf',
    'loganberries',
    'loin',
    'longans',
    'loquats',
    'lotus',
    'lulo',
    'lunch',
    'luncheon',
    'lupins',
    'luxury',
    'macaroni',
    'made',
    'malabar',
    'malt',
    'malted',
    'mammy-apple',
    'mango',
    'mangos',
    'mangosteen',
    'maraschino',
    'margarine',
    'margarine-like',
    'marmalade',
    'mashu',
    'mayonnaise',
    'meal',
    'meat',
    'meatballs',
    'meatloaf',
    'melon',
    'melons',
    'milk',
    'millet',
    'mint',
    'miso',
    'mocha',
    'molasses',
    'mollusks',
    'moose',
    'mortadella',
    'mothbeans',
    'mountain',
    'mouse',
    'muffin',
    'muffins',
    'mulberries',
    'mung',
    'mungo',
    'mush',
    'mushrooms',
    'mustard',
    'mutton',
    'nance',
    'naranjilla',
    'natto',
    'navajo',
    'nectar',
    'nectarines',
    'nettles',
    'noodles',
    'nopales',
    'nuts',
    'oat',
    'oats',
    'octopus',
    'oheloberries',
    'oil',
    'oil-butter',
    'okara',
    'okra',
    'olive',
    'olive oil',
    'olives',
    'onion',
    'onions',
    'oopah',
    'orange',
    'orange-flavor',
    'orange-grapefruit',
    'oranges',
    'ostrich',
    'oven-roasted',
    'palm',
    'pancakes',
    'papad',
    'papaya',
    'papayas',
    'parfait',
    'parmesan',
    'parsley',
    'parsnips',
    'passion-fruit',
    'pasta',
    'pastrami',
    'pastries',
    'pastry',
    'pate',
    'patties',
    'patty',
    'pea',
    'peach',
    'peaches',
    'peanut',
    'peanuts',
    'pear',
    'pears',
    'peas',
    'pectin',
    'peel',
    'people',
    'pepeao',
    'pepper',
    'peppered',
    'peppermint',
    'pepperoni',
    'peppers',
    'persimmons',
    'pheasant',
    'phyllo',
    'pickle',
    'pickles',
    'picnic',
    'pie',
    'pigeon',
    'pigeonpeas',
    'piki',
    'pimento',
    'pimiento',
    'pineapple',
    'pinon',
    'pitanga',
    'pizza',
    'plantains',
    'plums',
    'pockets',
    'pokeberry',
    'pomegranate',
    'pomegranates',
    'popcorn',
    'pork',
    'pork belly',
    'potato',
    'potatoes',
    'potsticker',
    'poultry',
    'powder',
    'prairie',
    'prepared',
    'preserves',
    'pretzels',
    'prickly',
    'product',
    'products',
    'protein',
    'prune',
    'prunes',
    'pudding',
    'puddings',
    'puff',
    'puffs',
    'pulled',
    'pulp',
    'pummelo',
    'pumpkin',
    'punch',
    'punch-flavor',
    'puppies',
    'puree',
    'purslane',
    'quail',
    'quarters',
    'queso',
    'quinces',
    'quinoa',
    'raab',
    'radicchio',
    'radish',
    'radishes',
    'raisins',
    'rambutan',
    'raspberries',
    'ravioli',
    'ready-to-drink',
    'ready-to-eat',
    'red',
    'red chilli',
    'red pepper',
    'reddi',
    'reduced',
    'refried',
    'relish',
    'rennin',
    'replacement',
    'restaurant',
    'rhubarb',
    'rice',
    'rice noodles',
    'rings',
    'roast',
    'rojos',
    'roll',
    'rolls',
    'root',
    'roots',
    'rose',
    'rose-apples',
    'roselle',
    'rosemary',
    'rowal',
    'ruffed',
    'rutabagas',
    'rye',
    'salad',
    'salami',
    'salmon',
    'salmonberries',
    'salsify',
    'salt',
    'sandwich',
    'sapodilla',
    'sapote',
    'sauce',
    'sauerkraut',
    'sausage',
    'scrapple',
    'seasoning',
    'seaweed',
    'seeds',
    'semolina',
    'sesbania',
    'sesame',
    'sesame oil',
    'sesame seeds',
    'shake',
    'shakes',
    'shallots',
    'shell',
    'shells',
    'sherbet',
    'shoots',
    'shortening',
    'shoyu',
    'side',
    'smelt',
    'smoothie',
    'snack',
    'snacks',
    'sorghum',
    'souffle',
    'soup',
    'sourdock',
    'soursop',
    'soy',
    'soy sauce',
    'soybean',
    'soybeans',
    'soyburgers',
    'soymilk',
    'spaghetti',
    'spanish',
    'spearmint',
    'spelt',
    'spices',
    'spinach',
    'split',
    'spread',
    'spring onion',
    'spring onions',
    'sprouts',
    'squab',
    'squash',
    'squirrel',
    'steelhead',
    'stew',
    'stew/soup',
    'stinging',
    'strawberries',
    'strawberry-flavor',
    'strudel',
    'stuffing',
    'substitute',
    'substitutes',
    'succotash',
    'sugar',
    'sugar snap peas',
    'sugar-apples',
    'sugars',
    'supplement',
    'swamp',
    'sweetener',
    'sweeteners',
    'swisswurst',
    'syrup',
    'syrups',
    'taco',
    'tamales',
    'tamari',
    'tamarind',
    'tamarinds',
    'tangerine',
    'tangerines',
    'tannier',
    'tapioca',
    'taquitos',
    'taro',
    'tart',
    'tea',
    'teff',
    'tempeh',
    'tenders',
    'tennis',
    'thigh',
    'thuringer',
    'thyme',
    'toast',
    'toaster',
    'toddler',
    'tofu',
    'tomatillos',
    'tomato',
    'tomatoes',
    'topping',
    'toppings',
    'tortellini',
    'tortilla',
    'tortillas',
    'tostada',
    'triticale',
    'trout',
    'tuber',
    'tunicate',
    'tunughnak',
    'turkey',
    'turnip',
    'turnips',
    'turnover',
    'turtle',
    'twists',
    'vanilla',
    'veal',
    'vegetable stock',
    'vegetable-oil',
    'vegetable oil',
    'vegetables',
    'vegetarian',
    'veggie',
    'vegetable or chicken stock',
    'chicken stock',
    'venison',
    'vermicelli',
    'vinegar',
    'vinespinach',
    'vital',
    'volteados',
    'waffle',
    'waffles',
    'walrus',
    'wasabi',
    'water',
    'waterchestnuts',
    'watercress',
    'watermelon',
    'waxgourd',
    'weed',
    'wheat',
    'whey',
    'whiskey',
    'wild',
    'willow',
    'wine',
    'winged',
    'wocas',
    'wonton',
    'wrappers',
    'yachtwurst',
    'yam',
    'yambean',
    'yardlong',
    'yautia',
    'yeast',
    'yellow',
    'yogurt',
    'yogurts',
    'zealand',
    'zwieback',
    'jalapeno chilli',
    'rigatoni',
    'farfalle',
    'brandy',
    'rum',
    'amaretto',
    'baileys',
    'tia maria',
    'anchovy fillet',
    'bay leaves',
    'bok choi',
    'mangetout',
    'szechuan peppercorns',
    'harissa',
    'cornflour',
    'mackerel',
    'leek',
    'shallot',
    'parsnip',
    'banana',
    'espresso',
    'brandy',
    'lemongrass',
    'coconut',
    'marmite',
    'paprika',
    'black peppercorns',
    'peppercorns',
    'ras el hanout',
    'jelly tablet',
    'jelly',
    'strawberry blancmange',
    'blancmange',
    'strawberry',
    'cachaça',
    'champagne ',
    'prosecco',
    'risotto',
    'risotto bianco',
    'atora shredded suet',
    'blanched almonds',
    'fudge',
    'pecans',
    'polenta',
    'pistachios',
    'peeled prawns',
    'bacardi carta blanco',
    'cointreau',
    'mussels',
    'shelled walnut',
    'brandy',
    'redcurrants',
    'cannelloni tubes',
    'cannelloni',
    'sponge fingers',
    'chipolata sausages',
    'cod fillet',
    'jersey royals',
    'meringue',
    'chardonnay',
    'silverbeet',
    'lettuces',
    'ciabatta',
    'grapefruits',
    'mangoes',
    'mango',
    'beetroot',
    'anise',
    'star anise',
    'horlicks',
    'treacle',
    'allspice',
    'sirloin steaks',
    'clams',
    'mozzarella',
    'pak choi',
    'camembert',
    'lasagne sheets',
    'greek yoghurt',
    'cider',
    'roasting spuds',
    'cornichons',
    'anchovies',
    'aubergines',
    'yolks',
    'cognac',
    'cornflour',
    'garam masala',
    'ketchup',
    'beansprouts',
    'mincemeat',
    'chanterelles',
    'crumpets',
    'flatbreads',
    'poussins',
    'chipolatas',
    'jam',
    'scallions',
    'meringues',
    'prosciutto',
    'courgettes',
    'aioli',
    'sirloins',
    'fillet steaks',
    'tuna steaks',
    'orecchiette',
    'tagliatelle',
    'juniper berries',
    'linguine',
    'yoghurt',
    'penne',
    'tuna',
    'guinness',
    'stout',
    'beer',
    'ale',
    'elderflower cordial',
    'gin',
    'vodka',
    'stock',
    'cloves',
    'whisky ',
    'chuck steak',
    'custard',
    'mascarpone',
    'portobello ',
    'desiccated coconut',
    'pancetta',
    'grappa',
    'summer savory',
    'chillies',
    'oregano',
    'calvados',
    'limoncello',
    'saffron',
    'breadcrumbs',
    'gherkins',
    'rocket',
    'flaked almonds',
    'walnuts',
    'butterghee',
    'chilli',
    'white vermouth',
    'sage',
    'amaretto',
    'angostura bitters',
    'cherry compote',
    'chilli salsa',
    'crème fraîche',
    'dressing',
    'french dressing',
    'fresh soft herbs',
    'natural yoghurt',
    'nutmeg',
    'oysters',
    'paste',
    'risotto',
    'risotto base',
    'salsa',
    'spice rub',
    'spicy mayo',
    'sponge',
    'clementine',
    'nutmeg',
    'chianti',
    'marjoram',
    'tarragon',
    'swede',
    'soda',
    'romaine',
    'turmeric',
    "bay leaf",
    "chestnuts",
    "blackcurrant cordial",
    "aubergine",
    "baguette",
    "cardamom pod",
    "bok choy",
    "champagne",
    "burger bun",
    "chervil",
    "chipolata",
    "clove",
    "courgette",
    "crumpet",
    "date",
    "flatbread",
    "fig",
    "scotch bonnet",
    "merlot",
    "marsala",
    "almonds",
    "biscotti",
    "marshmallows",
    "sultanas",
    "ricotta",
    "dukkah",
    "flaxseeds",
    "tahini",
    "sumac",
    "tandoori",
    "baharat",
    "cross bun",
    "courgette",
    "maris piper",
    "seven-spice",
    "gelatine",
    "dashi",
    "port",
    "nectarine",
    "martini bianco",
    "partridge",
    "mace",
    "charcoal",
    "chaat masala",
    "plantain",
    "quince",
    "satsuma",
    "nori",
    "bun",
    "mirin",
    "pimm’s",
    "tequila",
    "chervil",
    "caperberries",
    "cardamom pods",
    "dukkah",
    "glucose",
    "panch phoran",
    "tabasco",
    "armagnac",
    "sriracha",
    "chinese five spice",
    "cumin",
    "fenugreek",
    "kasoori methi",
    "linseed",
    "ras-el-hanout",
    "sambal oelek",
    "togarashi",
    "yuzu",
    "vin santo",
    "marsala",
    "sherry",
    "sweetcorn",
    "brisket",
    "cassia bark",
    "gammon",
    "feta",
    "sirloin steak",
    "jalapeños",
    "fillet steak",
    "tzatziki",
    "jalapeños",
    "chestnut purée",
    "beetroots",
    "beetroot",
    "buttermilk",
    "stir-fry veg",
    "lager",
    "passata",
    "mediterranean veg",
    "picanha",
    "cumberland sausage",
    "cumberland sausages",
    "pitta bread",
    "gianduja",
    "uda pods",
    "brie",
    "cavolo nero",
    "barberries",
    "frisée",
    "levain starter",
    "maltesers",
    "oatmeal",
    "orzo",
    "suet",
    "stilton",
    "cashews",
    "armagnac",
    "bourbon whisky",
    "crème de cassis",
    "triple sec",
    "cumberland sausages",
    "fruity boiled sweets",
    "poppadoms",
    "cheddar",
    "feta",
    "greek feta",
    "farmhouse cheese",
    "farmhouse cheeses",
    "cashews",
    "bucatini",
    "trofie",
    "fusilli",
    "urid dal",
    "dal",
    "galangal",
    "martini",
    "bresaola",
    "prawns",
    "tacos",
    "spaghettini",
    "haggis",
    "coppa di parma",
    "kiwi",
    "oxtail",
    "panettone",
    "t-bone steak",
    "za’atar",
    "kecap manis",
    "cauliflowers",
    "cucumbers",
    "frisée",
    "mayo",
    "pesto",
    "kiwis",
    "burrata",
    "sausages",
    "baguettes",
    "naan bread",
    "naan breads",
    "pak choy",
    "partridges",
    "pheasants",
    "flatbread",
    "pigeons",
    "pittas",
    "poppadoms",
    "quails",
    "rabbits",
    "passion fruit",
    "passion fruits",
    "sourdough",
    "dukkah",
    "hollandaise",
    "ghee",
    "ovaltine",
    "houmous",
    "sambal oelek",
    "tamarillos",
    "bee pollen",
    "herbes de provence",
    "saeujeot",
    "seven-spice",
    "za’atar",
    "za’tar",
    "lighter cubes",
    "pitta breads",
    "noodle",
    "lobsters",
    "flank steak",
    "tzatziki",
    "halloumi",
    "candy cane",
    "candy canes",
    "bucatini",
    "cavolo nero",
    "cornichon",
    "orzo",
    "farro",
    "berries",
    "kimchee",
    "sourdough starter",
    "tiger prawns",
    "porridge mix",
    "ricotta",
    "sprouting seed mix",
    "taglierini",
    "crabmeat",
    "bombay mix",
    "cashews",
    "deggi mirch",
    "’nduja",
    "ricotta salata",
    "marzipan",
    "king prawns",
    "rump steak",
    "tagliolini",
    "brown crabmeat",
    "white crabmeat",
    "porter",
    "gelatine",
    "galangal",
    "toulouse sausages",
    "passion fruits",
    "drambuie",
    "dukkah",
    "harrisa",
    "kirsch",
    "panettone",
    "brambles",
    "dripping",
    "hobnobs",
    "claws",
    "sorrel",
    "ipa",
    "madeira",
    "bombay mix",
    "créme fraîche",
    "fenugreek",
    "pecorino",
    "paneer",
    "fusilli",
    "pappardelle",
    "gnocchi",
    "shelled prawns",
    "rabbit thighs",
    "endives",
    "feather steaks",
    "drumstick",
    "drumsticks",
    "italian sausages",
    "baps",
    "filo pasty",
    "squid",
    "grand marnier",
    "chapatis",
    "skate",
    "partridge breasts",
    "flank skirt steak",
    "kiwi",
    "flank",
    "skirt",
    "merguez sausages",
    "steak",
    "monkfish",
    "cod",
    "haddock",
    "brie",
    "choi sum",
    "golden linseed",
    "linseed",
    "linseeds",
    "pinenuts",
    "stilton",
    "toffees",
    "armagnac",
    "bourbon",
    "sake",
    "scottish whisky",
    "drambuie",
    "courgette",
    "burgundy",
    "pinot noir",
    "aperol",
    "caramel sweets",
    "kimchee",
    "starter",
    "curd",
    "hung curd",
    "mangetouts",
    "rosewater",
    "tabasco",
    "chipotle tabasco",
    "dill",
    "dilll",
    "pecorino",
    "achiote recado",
    "recado",
    "aloo gobi",
    "banoffee",
    "baps",
    "bourbon",
    "porridge",
    "batter",
    "bircher",
    "biscuit",
    "bolognese",
    "briks",
    "brine",
    "brittle",
    "burger",
    "butcher's string",
    "buttercream",
    "béchamel",
    "caramel",
    "naan",
    "chestnut dumplings",
    "chowder",
    "cod",
    "coleslaw",
    "compote",
    "condiments",
    "crispbreads",
    "crostini",
    "croûtes",
    "crumble",
    "crème patissière",
    "crêpes",
    "dosa batter",
    "dumplings",
    "dumpling",
    "fajitas",
    "filling",
    "garnish",
    "garnishes",
    "glaze",
    "gratin",
    "gremolata",
    "grits",
    "herb crumb",
    "herb cure",
    "vinaigrette",
    "herb vinaigrette",
    "hoisin",
    "nutella",
    "honeycomb",
    "jerk marinade",
    "kebab",
    "kebabs",
    "laksa",
    "lasagne",
    "levain",
    "macerated berries",
    "manchego",
    "mash",
    "mayo",
    "mole",
    "monkfish",
    "neeps & tatties",
    "nougat",
    "oatmeal",
    "omelette",
    "pangrattato",
    "parathas",
    "plantain",
    "plum",
    "pomme purée",
    "ponzu",
    "raita",
    "raspberry",
    "sambal",
    "scallops",
    "fries",
    "shortbread",
    "shortcake",
    "slaw",
    "aubergine",
    "sofrito",
    "spice cure",
    "spice mix",
    "strawbs",
    "edible glitter",
    "sweets",
    "tabbouleh",
    "taco",
    "tacos",
    "daal",
    "tadka daal",
    "tapenade",
    "temper",
    "tempura batter",
    "toasts",
    "tzatziki",
    "vinaigrette",
    "butcher paper",
    "briquettes",
    "whisk",
    "white bloomer",
    "winter slaw",
    "yorkshire batter",
    "aniseed",
    "barolo",
    "pandan",
    "asafoetida",
    "fenugreek",
    "Cheddar",
    "Mozzarella",
    "Parmesan",
    "Swiss",
    "Brie",
    "Gouda",
    "Feta",
    "Blue Cheese",
    "Camembert",
    "Ricotta",
    "Goat Cheese",
    "Provolone",
    "Gruyère",
    "Havarti",
    "Colby",
    "Monterey Jack",
    "Asiago",
    "Mascarpone",
    "Pecorino",
    "Emmental",
    "Neufchâtel",
    "Cottage Cheese",
    "String Cheese",
    "Halloumi",
    "Cream Cheese",
    "Taleggio",
    "Queso Fresco",
    "Ricotta Salata",
    "Cotija",
    "Burrata",
]

foodItemList.sort(reverse=True)
