# Generated by Django 5.1.1 on 2024-09-12 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recipe_user_recipe_dishnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('externalId', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('proteinGram', models.FloatField()),
                ('carbsGram', models.FloatField()),
                ('fatGram', models.FloatField()),
                ('saturatedFatGram', models.FloatField()),
                ('saltGram', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nutrition'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nutrition'),
        ),
    ]
