# Generated by Django 5.1.1 on 2024-09-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='api.recipe'),
        ),
    ]
