# Generated by Django 5.1.1 on 2024-09-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_method_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField()),
                ('name', models.TextField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='skillLevel',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='api.recipe'),
        ),
        migrations.AddConstraint(
            model_name='method',
            constraint=models.UniqueConstraint(fields=('recipe', 'step'), name='unique_recipe_step'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='skill_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.skilllevel'),
        ),
    ]
