# Generated by Django 5.1.1 on 2024-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_skilllevel_remove_recipe_skilllevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='externalId',
            field=models.CharField(max_length=255),
        ),
    ]
