# Generated by Django 5.1.1 on 2024-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ingredient_externalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='level',
            field=models.IntegerField(),
        ),
    ]
