# Generated by Django 5.1.1 on 2024-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_method_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='imageUrl',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='origUrl',
            field=models.CharField(null=True),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('title', 'source'), name='unique_recipe_title_source'),
        ),
    ]
