# Generated by Django 5.1.1 on 2024-09-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_recipe_source_alter_recipe_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_100_gr_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='heb_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
