# Generated by Django 5.1.1 on 2024-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ingredient_cost_per_100_gr_ml_ingredient_heb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='externalId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
