# Generated by Django 5.1.1 on 2024-09-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ingredient_externalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='approximate_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
