# Generated by Django 5.1.1 on 2024-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_100_gr_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
